### ISSUE TITLE
services/README.md links to missing mgmt/resources/examples/*

### ISSUE THREAD

**Issue by rickrain** [Azure/azure-sdk-for-rust#704] opened 2022-03-29 15:58 UTC
The `group_create` example under [examples](https://github.com/Azure/azure-sdk-for-rust/blob/main/services/README.md#examples) links to missing code.

@cataggar, it appears that removing this sample was intentional based on [this commit](https://github.com/Azure/azure-sdk-for-rust/pull/527/commits/26f2b51736e3f204970e8ce3e6518e2ae4efce47) a few months ago.  Should we remove the reference to the sample from the README or re-create a new version of the sample to link to?  Personally, it seems like a good sample to have available for users.

**Comment by cataggar** [comment] 2022-03-30 10:10
See #528. The intention was to add it back. The issue is that the default tag doesn't contain the operations needed by that example. https://github.com/Azure/azure-sdk-for-rust/tree/main/services/mgmt/resources . This can be fixed by setting the default tag in the specification readme.

**Comment by cataggar** [comment] 2022-03-30 10:26
Here is a pull request: https://github.com/Azure/azure-rest-api-specs/pull/18475

**Comment by rickrain** [comment] 2022-04-01 16:06
Since the PR referenced above has been merged, I'm trying to understand what the next steps are.  It seems that the following needs to be done.
1. Using `./services/autorust, re-generate the `./azure-rest-api-specs/specification/...<abbreviated>`.
2. Using `./services/autorust`, codegen the `resources_mgmt`.
3. Restore the `group_create.rs` example.
4. Update workspace in `cargo.toml`.

Is this the process?

**Closed** 2022-04-03 07:56 UTC
