### ISSUE TITLE
policySetDefinition Group Names should be Option<>

### ISSUE THREAD

**Issue by mdtro** [Azure/azure-sdk-for-rust#241] opened 2021-05-05 00:21 UTC
Based on the Azure REST API Spec, the `groupNames` should be marked as optional.
The Microsoft Docs also notate it as optional, [see here.](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/initiative-definition-structure#policy-definition-properties)

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policySetDefinitions.json#L564-L574

```
        "groupNames": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The name of the groups that this policy definition reference belongs to."
        }
      },
      "required": [
        "policyDefinitionId"
      ],
```

It's rendered as in the `models.rs` for the 2019-09-01 version in this repo:

```
    #[serde(rename = "groupNames", default, skip_serializing_if = "Vec::is_empty")]
    pub group_names: Vec<String>,
```

https://github.com/Azure/azure-sdk-for-rust/blob/8d275a30e7cd857e38809c651516fc21e51c5ba0/services/mgmt/resources/src/package_policy_2019_09/models.rs#L204-L205

To fix this, would the lines just need to be adjusted to? If that sounds like the right path, I'm happy to look through the other API versions to make sure they align and contribute a PR. 

```rust
    #[serde(rename = "groupNames", default, skip_serializing_if = "Option::is_none")]
    pub group_names: Option<Vec<String>>,
```

**Comment by mdtro** [comment] 2021-05-05 00:41
This same scenario will apply to the `policyDefinitionGroups`.

**Comment by ctaggart** [comment] 2021-05-14 22:09
Hi @mdtro. By design, instead of ` Option<Vec<String>>>`, I chose to just do  `Vec<String>`. If it is empty, it will not be written. This makes the code much more pleasant to work with in my experience.

**Comment by mdtro** [comment] 2021-05-14 22:50
Ah, I understand, @ctaggart. 

My use case was deserializing a policyset definition from a JSON/ARM template file. It did not have the _policyDefinitionGroups_ or _groupNames_ fields and thus resulted in a serde error.

```
[...] missing field `groupNames` at line 35 column 13
```
The fix was to just add in the empty arrays within the JSON file. Here's a snippet:

```
        "policyDefinitionGroups": [],
        "policyDefinitions": [
            {
                "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/0b60c0b2-2dc2-4e1c-b5c9-abbed971de53",
                "parameters": {
                    "effect": {
                        "value": "Audit"
                    }
                },
                "groupNames": []
            },
```

It wasn't much trouble to go through each of my initiatives adding these fields. :)

**Comment by ctaggart** [comment] 2021-05-14 23:13
You may have run into bug https://github.com/Azure/azure-sdk-for-rust/pull/233, but the bug fix merged 25 days ago.

**Closed** 2021-05-15 01:06 UTC
Labels: services
