### ISSUE TITLE
Stream does not implement `Send`

### ISSUE THREAD

**Issue by kamlesh-nb** [Azure/azure-sdk-for-rust#752] opened 2022-05-18 14:27 UTC
I get the below error, 
```
future cannot be sent between threads safely
the trait `Send` is not implemented for `(dyn Stream<Item = Result<ListDocumentsResponse<workspace::WorkSpace>, azure_core::error::Error>> + 'static)`
required for the cast to the object type `dyn Future<Output = Vec<workspace::WorkSpace>> + Send`rustc
cosmos_service.rs(57, 20): future is not `Send` as this value is used across an await
cosmos_service.rs(53, 19): consider moving this into a `let` binding to create a shorter lived borrow
```
**Code**:
`let respo = self
            .client
            .list_documents()
            .into_stream::<WorkSpace>()
            .next()
            .await
            .unwrap().unwrap().documents;`

Could someone please help me?

**Comment by rylev** [comment] 2022-05-19 12:52
The issue is that the `Stream` returned from `list_documents().into_stream()` does not implement `Send` (i.e., in other words, it cannot be safely transferred between threads. I opened a PR #758 that requires that creating a stream in the SDK makes a stream that is thread safe and implements `Send`. With that fix, this issue should hopefully go away. Sorry for the headache!

**Closed** 2022-05-20 18:56 UTC

**Comment by kamlesh-nb** [comment] 2022-05-23 11:28
Similar issue, for QueryDocumentResponse

**Comment by rylev** [comment] 2022-05-30 10:52
@kamlesh-nb I'm not seeing that. I opened #773 to confirm.
