### ISSUE TITLE
Queue Storage GetMessages hides `message_id` and `pop_receipt` values

### ISSUE THREAD

**Issue by wilsonzlin** [Azure/azure-sdk-for-rust#1119] opened 2022-10-11 23:16 UTC
It appears that the SDK parses the `message_id` and `pop_receipt` IDs from the Queue Storage GetMessages response but then hides them behind a single `PopReceipt` Rust type with no way of getting the underlying values. While they are opaque values, it's still nice to be able to use them separately as the message ID uniquely identifies a message while the pop receipt identifies a specific dequeue. For example, logging/storing the message ID can track repeated deliveries and service latencies, while pop receipt identifies a specific job attempt and associated logs/metrics. Also, some APIs require/provide the message ID e.g. PeekMessages. The official Azure JS SDK appears to offer both as separate values, and require both when calling any API instead of a single opaque object.

**Comment by rylev** [comment] 2022-10-17 09:38
This is a duplicate of the issue being solved in #1114. I'll close this one, but you can follow along there.

**Closed by rylev** 2022-10-17 09:38 UTC
